name: code-red
authors: [ignpurple, radstevee, AndreasMelone]
version: 0.0.0
api-version: 1.21.1
main: com.github.inventorygamejam.codered.CodeRed
bootstrapper: com.github.inventorygamejam.codered.CodeRedBootstrapper
has-open-classloader: true
dependencies:
  - WorldEdit
  - FastAsyncWorldEdit